version: "3.8"

services:
  scrapper-service:
    build:
      context: ./scrapper-service
      dockerfile: Dockerfile
    command: npm run dev
    ports:
      - "3000:3000"
    depends_on:
      - rabbitmq
      - mongo
    env_file:
      - ./scrapper-service/.env

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    command: npm run dev
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
      - mongo
    env_file:
      - ./user-service/.env

  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
