version: "3.8"

services:
  scrapper-service:
    build:
      context: ./scrapper-service
      dockerfile: Dockerfile
    command: npm run dev
    ports:
      - "3000:3000"
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongo:
        condition: service_started
    env_file:
      - ./scrapper-service/.env
MNj1Dw4AAAAJ
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    command: npm run dev
    ports:
      - "8080:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongo:
        condition: service_started
    env_file:
      - ./user-service/.env

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: